### ISSUE TITLE
Gameplay: There is a huge bug in gameplay related to entering a word (WHISK is missing center letter, W)

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2023sp-420-G-J-IFY#232] opened 2023-03-09 01:42 UTC
Try it: base word of WHISKEY

**Comment by willkill07** [comment] 2023-03-09 01:53
<img width="812" alt="Screenshot 2023-03-07 at 11 46 38 AM" src="https://user-images.githubusercontent.com/2007799/223895286-14304d19-88f3-4809-9731-17797c6c0cb0.png">

**Comment by JMLovegren** [comment] 2023-03-16 19:11
Assigned to @JMLovegren

**Comment by JMLovegren** [comment] 2023-03-23 18:23
<img width="703" alt="Screenshot 2023-03-23 at 2 22 39 PM" src="https://user-images.githubusercontent.com/122911888/227311227-99
<img width="703" alt="Screenshot 2023-03-23 at 2 22 55 PM" src="https://user-images.githubusercontent.com/122911888/227311248-003f87e7-1d87-489f-88ed-e760aee84fb8.png">
7a7143-ec18-4825-80a0-87956584484d.png">

**Comment by JMLovegren** [comment] 2023-03-23 18:23
<img width="703" alt="Screenshot 2023-03-23 at 2 22 55 PM" src="https://user-images.githubusercontent.com/122911888/227311337-7a488434-7501-4c03-b93f-86bbd26c991b.png">

**Comment by JMLovegren** [comment] 2023-03-23 18:24
We've not been able to recreate this issue. Was this a game started in our application, or loaded from another team's save?

**Comment by willkill07** [comment] 2023-03-24 19:22
You commenting two weeks later is too late for me to provide a reproducer.

**Comment by JMLovegren** [comment] 2023-03-24 19:24
I’ll work through this on my end. That should give me find the big

**Comment by JMLovegren** [comment] 2023-03-29 23:31
I've been able to reproduce this bug form another teams save. One more question (I know its been a while since this, so if you don't recall that's ok), did you guess those 3 words in our game or load them in with a save?

**Comment by willkill07** [comment] 2023-03-29 23:32
I loaded those with a save.

**Comment by JMLovegren** [comment] 2023-03-29 23:37
Excellent, then I think I have this pegged. 

Looks like the team I'm loading this in from is saving their word dictionary as a list of lists, where each word is its own list. This is against the agreed upon save standard, and causing the issue seen above. The missing center letter is the else case of our guess checker, which is why that's the feedback its delivering. 

I'm working now on a patch for this issue now that I identified what is causing it

**Comment by JMLovegren** [comment] 2023-03-29 23:37
![Screenshot 2023-03-29 at 7 37 31 PM](https://user-images.githubusercontent.com/122911888/228691271-5b179557-4ada-4de7-a27c-0c9601491d49.png)
![Screenshot 2023-03-29 at 7 37 42 PM](https://user-images.githubusercontent.com/122911888/228691278-054fdae5-2897-4029-ab9e-07a9f00a34d1.png)

**Closed** 2023-03-29 23:52 UTC
Labels: bug
